development:
 adapter: postgresql
 database: brassbull_development
test:
 adapter: postgresql
 database: brassbull_test
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: <%= ENV['DATABASE_URL'] %>
