development:
 adapter: postgresql
 url: <%= ENV['DATABASE_URL'] %>
test:
 adapter: postgresql
 database: brassbull_test
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>
